### ISSUE TITLE
Behavior of offsetTrail' seems to be changed in diagrams-2.0

### ISSUE THREAD

**Issue by wkoiking** [cchalmers/diagrams-dev#3]
In diagrams-1.4, following code produces the below image:
~~~
renderTest :: IO ()
renderTest = saveDiagram Cairo "XXX.png" (mkWidth 1000) $ hsep 0.5 [sample1, sample2] # fc green # fillRule Winding
 where m = 0.05
       sample1 = center $ strokeLocTrail $ offsetTrail' (with & offsetJoin .~ LineJoinRound) 0.15 baseLocTrail

       sample2 = center $ strokeLocTrail $ offsetTrail' (with & offsetJoin .~ LineJoinRound) (- 0.15) baseLocTrail

       baseLocTrail = (`at` origin) $ wrapLoop $ closeLine $ fromOffsets [V2 0 (negate 0.65), V2 (0.9 - m) m, V2 m (0.65 - m)]

strokeLocTrail :: Located (Trail V2 Double) -> NormalDiagram
strokeLocTrail = strokePath . fromLocTrail
~~~
![diagrams1](https://user-images.githubusercontent.com/3189740/55523490-88c98e00-56c4-11e9-9aef-58dae01ac6f2.png)

In diagrams-2.0, the seemingly the same code below produces the different image:
~~~
renderTest :: IO ()
renderTest = renderCairo "XXX.png" (mkWidth 1000) $ hsep 0.5 [sample1, sample2] # fc green # fillRule Winding
 where m = 0.05
       sample1 = center $ strokeLocTrail $ offsetTrail' (with & offsetJoin .~ LineJoinRound) 0.15 baseLocTrail

       sample2 = center $ strokeLocTrail $ offsetTrail' (with & offsetJoin .~ LineJoinRound) (- 0.15) baseLocTrail

       baseLocTrail = (`at` origin) $ wrapLoop $ closeLine $ fromOffsets [V2 0 (negate 0.65), V2 (0.9 - m) m, V2 m (0.65 - m)]
~~~
![diagrams2](https://user-images.githubusercontent.com/3189740/55523531-b7dfff80-56c4-11e9-8652-6f3d42ac0c76.png)

I think that the former one is expected behavior.

**Comment by cchalmers** [comment]
Maybe fixed (fixed for this example at least) with diagrams/geometry@bc34a9436869bb9a3c2841dc91361e8eb721fc39. Literally the first thing I tried was deleting a random `-` and it appeared to work...

We really need more tests for this code. If you can come up with more examples I'll add them https://github.com/diagrams/diagrams-backend-tests
