### ISSUE TITLE
extrudeBottom, extrudeTop, extrudeEnvelope behave differently in diagrams-2.0

### ISSUE THREAD

**Issue by wkoiking** [cchalmers/diagrams-dev#4]
`extrudeBottom`, `extrudeTop` and `extrudeEnvelope` behave differently in diagrams-2.0.
In diagrams-1.4, following code produces the below image:

~~~
renderTest :: IO ()
renderTest = renderCairo "XXX.png" (mkWidth 1000) $ showOrigin $ showEnvelope $ extrudeTop 1 $ extrudeBottom 1 $ rect 1 1
~~~

![XXX](https://user-images.githubusercontent.com/3189740/55771414-9e183100-5aa5-11e9-8a5b-149745245733.png)

In diagrams-2.0, the seemingly the same code below produces the different image:

~~~
renderTest :: IO ()
renderTest = saveDiagram Cairo "XXX.png" (mkWidth 1000) $ showOrigin $ showEnvelope $ extrudeTop 1 $ extrudeBottom 1 $ rect 1 1
~~~

![XXX](https://user-images.githubusercontent.com/3189740/55771431-ac664d00-5aa5-11e9-83e9-be92327907b2.png)

I think that the former one is expected behavior.

I have not prepared example for `extrudeEnvelope`. But I noticed similar kind of difference in my application currently migrating to diagrams-2.0.

**Comment by cchalmers** [comment]
Thanks for the report. I think I've fixed it with cchalmers/diagrams@33d961a32bbe2b2b785ad233184aef881c3a3dd5. You're making me realise that I need much better test coverage.

**Comment by wkoiking** [comment]
I have checked with 33d961a however there still seems to be some difference between the two.
In diagrams-1.4, somehow the `extrudeEnvelope v` seems to extend the envelope half the magnitude of given vector `v`  whereas in 33d961a, it extend exactly `v`. The current behavior seems to be more reasonable but I want to know the reason why it used to be that way.

**Comment by cchalmers** [comment]
It was a bug (diagrams/diagrams-lib@d571420fa37cdfa3f86a953a13dc456adbe52654). I guess the fix hasn't been pushed to hackage yet.

**Comment by wkoiking** [comment]
I have just noticed that the intruding direction by `intrudeEnvelope v` seems to be opposite in diagrams-2.0 as compared to diagrams-1.4. Although current behavior is understandable, one need to be careful when migrating.

**Comment by wkoiking** [comment]
I have just created new issue #6 for that.
