### ISSUE TITLE
Opposite direction is intruded by `intrudeEnvelope v` in diagrams-1.4 and diagrams-2.0

### ISSUE THREAD

**Issue by wkoiking** [cchalmers/diagrams-dev#6]
I have just noticed that the intruding direction by intrudeEnvelope v seems to be opposite in diagrams-2.0 as compared to diagrams-1.4. Although current behavior is understandable, one need to be careful when migrating.

**Comment by byorgey** [comment]
Hi @wkoiking , thanks for the report!  Do you have an example that shows the difference?

**Comment by wkoiking** [comment]
`showOrigin $ showEnvelope $ intrudeEnvelope unitX $ circle 5` in diagrams-1.4 and diagrams-2.0 is as below respectively:
![YYY](https://user-images.githubusercontent.com/3189740/56804877-28acae80-6862-11e9-9101-c5ae84315a04.png)
![CCC](https://user-images.githubusercontent.com/3189740/56804891-35310700-6862-11e9-9fe8-450a054db624.png)

Note: The extent of the intrusion differ due to https://github.com/cchalmers/diagrams-dev/issues/4#issuecomment-482786474

**Comment by byorgey** [comment]
Thanks for the example.  Do you know if `extrudeEnvelope` is similarly reversed?  Or is it only `intrudeEnvelope`?

**Comment by wkoiking** [comment]
Only `intrudeEnvelope` is reversed.

**Comment by byorgey** [comment]
I think I have figured it out, I just need to do some testing before pushing a fix.

**Comment by wkoiking** [comment]
But current behavior for diagrams-2.0 seems more reasonable for me. So only mentioning on some documentation may be OK.

**Comment by byorgey** [comment]
Yes, I can see the difficulty with the "most intuitive" meaning for `intrudeEnvelope`: does the direction point to the part of the envelope that will be modified?  Or does it tell you the direction in which the envelope will be pushed?  I can see the argument for both.

**Comment by byorgey** [comment]
I clarified the documentation --- let me know if you think it makes sense!

**Comment by wkoiking** [comment]
I checked the comment and have no issue. Thank you for updating according to my preference.
