### ISSUE TITLE
Sampling of rotated diagram is not right

### ISSUE THREAD

**Issue by wkoiking** [cchalmers/diagrams-dev#9]
As shown in the below example, sampling of rotated diagram seems not right when concatenated with other diagram.

~~~
import System.Random (randomRIO)
import Control.Monad (replicateM)

test :: FilePath -> IO ()
test file = do
    ds <- mapM testSampling [d1, d2, d3]
    saveDiagram Cairo file (mkWidth 1000) $ hsep 1 ds

testSampling :: Diagram V2 -> IO (Diagram V2)
testSampling d = do
    points <- replicateM 1000 (mkP2 <$> rand10 <*> rand10)
    return $ d # lw thick <> position (map (mkPoint d) points)

d1, d2, d3 :: Diagram V2
d1 = vcat
    [ rotate (60 @@ deg) $ triangle 10
    ]
d2 = vcat
    [ rect 5 5
    , rotate (60 @@ deg) $ triangle 10
    ]
d3 = vcat
    [ rect 5 5
    , triangle 10
    ]

mkPoint d p = (p, circle 0.3
                # lw none
                # fc (case inquire d p of
                        True  -> red
                        False -> blue
                     )
            )

rand10 :: IO Double
rand10 = randomRIO (-10,10)
~~~

![BBB](https://user-images.githubusercontent.com/3189740/58958592-e3fd2700-87c0-11e9-88be-861ed1ad2dde.png)

The sampling of `d2` seems wrong while other two seems to be okay.

**Comment by wkoiking** [comment]
Hope someone knowledgeable look into this issue. Since this is only remaining issue which prevent me to migrate to diagrams-2.0 so far.

**Comment by byorgey** [comment]
Sorry no one has responded yet.  I will try to take a look at this soon.

**Comment by cchalmers** [comment]
Oh right sorry. I did look into it and I think I know how to solve the problem but then I got pretty busy and haven't had time to do any diagram stuff.

As I understand it the current diagrams also suffers from this issue and it requires a change to how queries work, but I could be mistaken.

**Comment by wkoiking** [comment]
> As I understand it the current diagrams also suffers from this issue and it requires a change to how queries work, but I could be mistaken.

I do not think current diagrams has the same issue. I have been using sample function in diagrams-1.4 quite often and had no issue. I have noticed this issue since some object in my app became not click-able after I have migrated my app to diagrams-2.0.

**Comment by cchalmers** [comment]
Sorry again for taking so long to get to this. Turns out there was a mistake in the matrix inversion code (kinda surprised none of the other tests caught this). Pushed the fix (diagrams/geometry@3e623ee1083def7974a446a74dff302c8f73c6b9) and also added a query test to diagrams-backend-tests (diagrams/diagrams-backend-tests@b06aff5).

**Comment by wkoiking** [comment]
Thanks for the fix.

However, after the fix, while the particular test case seems to be now Okay, clicking for my application seems not working at all.

Also when you define the transformation by
~~~
(A, b) x = A x + b
~~~
where `A` is matrix and `b` is vector, its inversion should be:

~~~
A^(-1) (x - b) = A^(-1) x - A^(-1) b = (A^(-1), - A^(-1) b)
~~~
Hence rather previous implementation looks correct for me.

Could you confirm that the fix is right?

**Comment by wkoiking** [comment]
Also I found counter case for (https://github.com/diagrams/geometry/commit/3e623ee1083def7974a446a74dff302c8f73c6b9) as below:

~~~
test :: FilePath -> IO ()
test file = do
    ds <- mapM testSampling [d4]
    saveDiagram Cairo file (mkWidth 1000) $ hsep 1 ds

testSampling :: Diagram V2 -> IO (Diagram V2)
testSampling d = do
    points <- replicateM 1000 (mkP2 <$> rand10 <*> rand10)
    return $ d # lw thick <> position (map (mkPoint d) points)

d4 :: Diagram V2
d4 = scale 1.1 $ translateX 5 $ circle 2

mkPoint d p = (p, circle 0.3
                # lw none
                # fc (case inquire d p of
                        True  -> red
                        False -> blue
                     )
            )

rand10 :: IO Double
rand10 = randomRIO (-10,10)
~~~

![Test](https://user-images.githubusercontent.com/3189740/64161907-61483e80-ce79-11e9-8028-6492c7058bcb.png)

Still sampling of d4 seems wrong when you combine scaling.
And this test case was Okay in previous implementation.

**Comment by wkoiking** [comment]
Furthermore, I think the correctness previous implementation of `inv` can be confirmed as follow:
~~~
inv (inv (T m mInv v)) 
    = inv (T mInv m (negated v *! mInv))
    = (T m mInv (nagated (negated v *! mInv) *! m)
    = (T m mInv v)
~~~

So I'm positive that there should be other cause of this issue (that may be specific to Query which I'm not sure).

<Edit>
The above argument holds after the fix as well. So you can ignore this comment. Anyway I believe previous implementation is right.

**Comment by cchalmers** [comment]
Right. I've had another go at it with diagrams/geometry@067f809. This pretty much matches the [diagrams-core version](https://github.com/diagrams/diagrams-core/blob/master/src/Diagrams/Core/Transform.hs#L165-L167) so I hope it's right this time.

**Comment by wkoiking** [comment]
Thanks for the fix!
I confirmed everything is fine now.
I also assumed `*! = flip (!*)` but come to think of it, `Ax` and `xA` was different in school as well.
